### ISSUE TITLE
Region cache stuck once try to load region until +inf

### ISSUE THREAD

**Issue by YuJuncen** [tikv/client-go#1051]
I have noticed this call never return:
```go
	rs, err := c.Cache.LoadRegionsInKeyRange(bo, startKey, []byte(""))
```
According to `dlv`, this call generated a infinite loop in `github.com/tikv/client-go/v2/internal/locate.(*RegionCache).LoadRegionsInKeyRange()`, which tests whether the last region contains the end key is by a buggy function:
```go
// ContainsByEnd check the region contains the greatest key that is less than key.
// for the maximum region endKey is empty.
// startKey < key <= endKey.
func (r *Region) ContainsByEnd(key []byte) bool {
	return bytes.Compare(r.meta.GetStartKey(), key) < 0 &&
		(bytes.Compare(key, r.meta.GetEndKey()) <= 0 || len(r.meta.GetEndKey()) == 0)
}
```
The left hand side of `&&` simply always evaluates to `false` when the `key` is empty (which means inf). Which returns a false `false` when the input region has range `(*, +inf]`.

**Comment by disksing** [comment]
fixed.
