### ISSUE TITLE
Imporve failpoint performance

### ISSUE THREAD

**Issue by disksing** [tikv/client-go#145]
In order to move code here. We migrated failpoints to a fashion that need no code generation, which means it brings more performance cost. We can improve it by introducing a new global bool flag. After that  in most cases the only cost is to check the boolean.

**Comment by tiancaiamao** [comment]
![Lark20210625-104927](https://user-images.githubusercontent.com/1420062/123362367-23af2b00-d5a3-11eb-9dc7-1414ca1f1753.png)

It is a problem, failpoint is in the hot code path, and if the path does not exist, the failpoint throw a not exist error.
The error include the stack trace, and the error is frequent, so it impact the performance a lot!
