### ISSUE TITLE
Export CommitTS of KVTxn

### ISSUE THREAD

**Issue by b6g** [tikv/client-go#1488]
The `CommitTS` of an AsyncCommit transaction is determined from TiKV's `max_ts`. We need it to check the order of the timestamps in TiDB, as described in https://github.com/pingcap/tidb/issues/57165.

**Comment by cfzjywxk** [comment]
The already exists [`tidb_last_txn_info`](https://docs.pingcap.com/tidb/stable/system-variables#tidb_last_txn_info-new-in-v409) could be used to track the last transaction information in current session.
