### ISSUE TITLE
txnkv: make scan batchSize configurable

### ISSUE THREAD

**Issue by disksing** [tikv/client-go#191]
User may want to use a very large scan batchSize to improve performance. See https://github.com/tikv/client-go/issues/189

**Comment by gotoxu** [comment]
@disksing I'll handle this

**Comment by sticnarf** [comment]
If you want to set the batch size to a large value, the current TiKV has a problem that the scan requests may slow down light requests like point get. @gotoxu 

I open https://github.com/tikv/tikv/pull/9594 to solve the problem for kv_scan.

**Comment by gotoxu** [comment]
@sticnarf In fact, my original intention was to set a smaller scanBatchSize instead of returning const KVPairs :)

**Comment by disksing** [comment]
Fixed by https://github.com/tikv/client-go/pull/204
