### ISSUE TITLE
V2.0.0 release plan?

### ISSUE THREAD

**Issue by slow-zhang** [tikv/client-go#240]
I found a `- warning: The v2 branch is still being refactored and sorted out, and external interfaces may change before the v2.0.0 release. Please use caution in production environments.` in `client-go/ReadMe`. I am curious about when will this release happen and what needs to do to make it release

**Comment by disksing** [comment]
Hi @slow-zhang , at the moment we are concentrating on adding examples to demonstrate the usage of the features, while we will adjust the external API to make it easier to use at the same time. Then we will add the documentation for most of the features. Once this is done, it will be ready for release.

**Comment by slow-zhang** [comment]
thank you for quickly reply @disksing
