### ISSUE TITLE
Release v2.0.0 stable version

### ISSUE THREAD

**Issue by disksing** [tikv/client-go#287]
We plan to release v2.0.0 GA version of stable API after the following tasks are completed. The target release date is by December 1, 2021.

The pending tasks are as follows.
- [x] https://github.com/tikv/client-go/issues/177
- [ ] ~~https://github.com/tikv/client-go/issues/101~~
- [x] https://github.com/tikv/client-go/issues/63
- [x] #288
- [x] #289

**Comment by maoueh** [comment]
I would like to push for the `etcd`/`grpc` dependencies are up to date across the board. I understand it trickles down in lot of other `tikv` projects.

But pulling `tikv/client-go` makes it impossible to bump `grpc` nor `etcd` to their latest value. Anything I can do to help, I'll do to have this included.

It's really a pain right now. 

Thanks in advance!

**Comment by disksing** [comment]
@maoueh Thank you for raising this issue, I have added it to the list and managed to put the preceding issue to the roadmap schedule of the PD project. Hopefully, we will upgrade it after the PD upgrade is completed before the release.

**Comment by maoueh** [comment]
@disksing That's great news, thank you! Like I said previously, anything I can do to help around this, I'll gladly step in, be it development, testing, debugging, etc.

I'll track the various issues.

**Comment by franklinkim** [comment]
Hi, any updates on the pending tasks?

**Comment by disksing** [comment]
Sorry, we will have to delay for 2 more weeks. Mainly due to etcd upgrade issue :(

**Comment by slow-zhang** [comment]
Hi @disksing , any updates on the pending tasks?

**Comment by disksing** [comment]
We have released an rc version. Now you can `go get github.com/tikv/client-go/v2` directly.

**Comment by qiaohao9** [comment]
> We have released an rc version. Now you can `go get github.com/tikv/client-go/v2` directly.

How about `Upgrade etcd/grpc version`, any progress?

**Comment by killzoner** [comment]
Hey, just did https://github.com/tikv/client-go/pull/421 doing the `etc/grpc` upgrade, which might unblock this.
