### ISSUE TITLE
change on `OnSendFailForTiFlash` breaks compatibility test

### ISSUE THREAD

**Issue by iosmanthus** [tikv/client-go#312]
Pull request: https://github.com/tikv/client-go/pull/309 introduces a change on `OnSendFailForTiFlash`, which doesn't sync to TiDB master and break compatibility test. We should update the TiDB's client-go dependency. @windtalker @disksing

**Comment by disksing** [comment]
I thought there is already a TiDB PR :(
Please take a look @windtalker

**Comment by windtalker** [comment]
Yes, the related TiDB pr is https://github.com/pingcap/tidb/pull/28367

**Comment by disksing** [comment]
Fixed.
