### ISSUE TITLE
Import error while using v2.0.0-alpha 

### ISSUE THREAD

**Issue by RishiRavikumar** [tikv/client-go#319]
Hi,

I'm trying to import github.com/tikv/client-go/v2/tikv into a fresh project and am running into this error

>github.com/tikv/client-go/v2/tikv imports
>   go.etcd.io/etcd/clientv3 tested by
>   go.etcd.io/etcd/clientv3.test imports
>   go.etcd.io/etcd/integration imports
>   go.etcd.io/etcd/proxy/grpcproxy imports
>   google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.41.0), but does not contain package google.golang.org/grpc/naming

How do I resolve this?

Thanks

**Comment by disksing** [comment]
As etcd is upgraded now. I'll close it. If you still encounter errors, please reopen it or open new issue. Thanks!
