### ISSUE TITLE
Why no tag on this package?

### ISSUE THREAD

**Issue by yufeiminds** [tikv/client-go#36]
Hello,

Why no tag on this package? How to lock the version of this client?

Suggest to add release tag on it, then we will upgrade it by minor/patch. 

Best Regards

**Comment by shafreeck** [comment]
Thanks for your interest in this project, it is in a pretty early stage of developing and the first release has not been released. Now we are paying more attention to this project and the first version will be released soon.

**Comment by yufeiminds** [comment]
🎉🎉
