### ISSUE TITLE
The os.ReadFile used in tikv is the api of go version 1.16, 1.15 cannot be compiled successfully

### ISSUE THREAD

**Issue by sotowang** [tikv/client-go#384]
file: security.go

github.com/tikv/client-go/v2/config
../../../../pkg/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211118154139-b11da6307c6f/config/security.go:69:13: undefined: os.ReadFile
note: module requires Go 1.16

**Comment by sticnarf** [comment]
We've bumped the minimal support go version to 1.16 in https://github.com/tikv/client-go/pull/379.

Go 1.15 has reached EOL. I also recommend you to update your go version :)
