### ISSUE TITLE
Can I set BatchPut TTL to empty slice if I want infinite TTL?

### ISSUE THREAD

**Issue by YikSanChan** [tikv/client-go#408]
Currently, BatchPut takes TTL as args

```go
func (c *Client) BatchPut(ctx context.Context, keys, values [][]byte, ttls []uint64) error { ... }
```

If I want infinite TTL, can I simply pass in an empty slice `[]uint64{}`?

Thanks

**Comment by sticnarf** [comment]
cc @andylokandy

**Comment by andylokandy** [comment]
> If I want infinite TTL, can I simply pass in an empty slice []uint64{}?

Yes, it is the right way.

BTW, I think ttl is better to be moved to a more specific method like `BatchPutTTL`.
