### ISSUE TITLE
DeleteRange: inclusive or exclusive startKey and endKey?

### ISSUE THREAD

**Issue by YikSanChan** [tikv/client-go#409]
I want to confirm in the DeleteRange method:

```go
func (c *Client) DeleteRange(ctx context.Context, startKey []byte, endKey []byte) error { ... }
```

Which is correct?
- [startKey, endKey]
- [startKey, endKey)
- (startKey, endKey]
- (startKey, endKey)

Thanks.

**Comment by sticnarf** [comment]
It's [startKey, endKey). Left inclusive, right exclusive.

**Comment by YikSanChan** [comment]
@sticnarf Created a small PR to add the docs https://github.com/tikv/client-go/pull/412
