### ISSUE TITLE
What error type should be used when max sleep time of backoff exceeded?

### ISSUE THREAD

**Issue by sticnarf** [tikv/client-go#415]
Now we return the error of the first backoff type:

https://github.com/tikv/client-go/blob/d2281509972049b341132b08f9c6eae921f1c456/internal/retry/backoff.go#L154

But it is possible that after some rounds of retries, the error leading to the final timeout is different. Reporting the first backoff error may confuse the user. Is it better to return the last backoff or the most frequent backoff type?

cc @cfzjywxk @disksing

**Comment by cfzjywxk** [comment]
Returning the last backoff type seems to be fine, the detailed backoff information including the most frequent backoff type could be printted in the error log.

**Comment by sticnarf** [comment]
At the very beginning, the last backoff is used, while https://github.com/pingcap/tidb/issues/6793 claims using the first backoff is sometimes better.

So this leads me to thinking that the most frequent backoff may be a better idea.

Of course I think the log should include more information instead of only the latest backoff cfg.

**Comment by cfzjywxk** [comment]
Make sense, the most frequent backoff may help more to reveal the root cause for issues https://github.com/pingcap/tidb/issues/6793 describes, to answer what takes so long to backoff seems to be more useful to answer what makes the backoff timeout finally.

**Comment by sticnarf** [comment]
In #416, I choose the backoff that sleeps longest, considering different backoffs may vary a lot in their sleep base and cap, so it may be not so fair to use the frequency.
