### ISSUE TITLE
empty value is not supported

### ISSUE THREAD

**Issue by al8n** [tikv/client-go#418]
Hi, the client does not allow users to put a key with an empty value. But I think the key with an empty value is quite reasonable, sometimes, we do not care about the value, but we care about whether the key is in the database.
Is there any plan to support the key with an empty value?

**Problem:**
`Put(context.Background(), []byte("k"), []byte{})` will get `"empty value is not supported"`

**Comment by disksing** [comment]
duplicated with #87

It's a problem that is not easy to fix. Mainly because of membuffer uses empty value to mark delete. Now the easy way to overcome this issue is to use some _invalid value_ (such as ' ' or '_') based on your application.
