### ISSUE TITLE
The pessimistic lock acquired after retry could be resolved

### ISSUE THREAD

**Issue by cfzjywxk** [tikv/client-go#420]
The ttl for a pessimistic lock is [calculated](https://github.com/tikv/client-go/blob/master/txnkv/transaction/pessimistic.go#L100) before locking loop. In some situations the pessimistic lock is acquired after doing retry or some lock wait which may take some time, the lock could be regareded as expired though it's just acquired for a while. For example:
![image](https://user-images.githubusercontent.com/3692139/153348865-f1333e6c-ccfd-423a-a11f-2847794b33c3.png)

1. In session 1 the rowkey `id=1` is locked.
2. In session 2 it tries to lock the same rowkey and starts to wait for the lock release.
3. In session 3 the session 1 is killed. After which the lock on `id=1` is released.
4. Session 2 locks the key successfully after waiting for some time.
5. Session 1 it reconnects and starts to try to lock the same rowkey again. It resolves the pessimisitc lock acuired just by the session 2, so the update succeeds.
6. The commit for transaction in session 2 will fail as the pessimistic lock is resolved already.

A possible optimization to avoid such failures is to use the newly calculated lock ttl before retrying to lock the same key.

**Comment by sticnarf** [comment]
Is it right https://github.com/tikv/client-go/pull/417 going to fix?

**Comment by cfzjywxk** [comment]
> Is it right #417 going to fix?

@sticnarf 
Yes, thanks for reminding I'm just trying to prepare a pr. We have encountered this issue in some customer's workload in which the application cares about the lock acquisition order and successful rate.

**Comment by cfzjywxk** [comment]
Fixed by #417.
