### ISSUE TITLE
Txnclient report error as `failed to decode region range key` when use client-java import kvs into tikv

### ISSUE THREAD

**Issue by guoxiangCN** [tikv/client-go#454]
After i ingest 1000000 kv pairs into tikv use tikv/client-java, all projects used tikv/client-go do the SCAN operation by KvTxn.Iter 
will report the error: ``failed to decode region range key`` 

this error reported from pd_codec.go/processRegionResult(), can anybody help me ? thanks

**Comment by guoxiangCN** [comment]
the ingest code 
`            KVClient kvClient = session.createKVClient();
            for (int j = 0; j < 1000000; j++) {
                String key = String.format("ns007:000:M:test_java_cli_key_%010d",j);
                String value = String.format("value_20220322_%d",j);
                datum.add(Pair.create(ByteString.copyFromUtf8(key), ByteString.copyFromUtf8(value)));
            }
            kvClient.ingest(datum);`

**Comment by disksing** [comment]
Do you write data using raw kv? If so, you need to use raw kv (https://github.com/tikv/client-go/wiki/RawKV-Basic) client of client-go too.

**Comment by guoxiangCN** [comment]
> 

I ingest the kv pairs into the tikv by java client's KVClient (not rawClient and not SmartRawClient), 
and scan the kv pairs from the tikv by golang's TxnClient too.
but i am not sure if there has raw-kv test datum in the tikv since it's a testing tikv cluster.

**Comment by disksing** [comment]
> > 
> 
> I ingest the kv pairs into the tikv by java client's KVClient (not rawClient and not SmartRawClient), and scan the kv pairs from the tikv by golang's TxnClient too. but i am not sure if there has raw-kv test datum in the tikv since it's a testing tikv cluster.

Yes it could be the reason. They cannot mix use.

**Comment by guoxiangCN** [comment]
Thanks for your reply :)  Could you tell me how to make it resume to work well ?  how can i picks the raw kv datum and remove it ?

**Comment by disksing** [comment]
If you know the key range of raw kv data (for example, all keys have the same prefix), you can use rawkv delete range command to clean up data, and then you will need merge all regions belong the the range (to estimate region keys). I'd like to set up a new cluster if it is not in a production environment.

**Comment by guoxiangCN** [comment]
> If you know the key range of raw kv data (for example, all keys have the same prefix), you can use rawkv delete range command to clean up data, and then you will need merge all regions belong the the range (to estimate region keys). I'd like to set up a new cluster if it is not in a production environment.

ok, thanks and i will try it.  And i have another question about import： 
It seems that we don't need to specify the client type (TxN or raw) to use importSST rpc service.  How does tikv determine the encoding after receiving these kvs data?

**Comment by disksing** [comment]
AFAIK, rawkv does not support data import, so it should can only import txnkv data.

**Comment by guoxiangCN** [comment]
> AFAIK, rawkv does not support data import, so it should can only import txnkv data.

i see. i found the importSST support stream write to gen sst (both raw and txn).  thanks.
I found that the reason of this issue's problem was caused by some bugs for tikv/clieng-java !!!
