### ISSUE TITLE
where is the error ErrStartTSFallBehind in v2?

### ISSUE THREAD

**Issue by ca1e** [tikv/client-go#475]
there is an error ErrStartTSFallBehind in v1 api, but I cant find it in v2, does it renamed or removed? if so, what error should I use instead

**Comment by sticnarf** [comment]
I find it is renamed to `GCTooEarly`:

https://github.com/tikv/client-go/blob/v2/tikv/kv.go#L156

**Comment by ca1e** [comment]
> I find it is renamed to `GCTooEarly`:
> 
> https://github.com/tikv/client-go/blob/v2/tikv/kv.go#L156

thanks! but how can I handle this error while the txnkv return? errors.Is seems not work...

**Comment by ca1e** [comment]
> I find it is renamed to `GCTooEarly`:
> 
> https://github.com/tikv/client-go/blob/v2/tikv/kv.go#L156

thanks! but how can I handle this error while the txnkv return? errors.Is seems not work...

**Comment by sticnarf** [comment]
I haven't tried it on my own, but I can give you some reference about how TiDB handles it:

https://github.com/pingcap/tidb/blob/89410b537f62305deec94068950be6fcd0fbcef4/store/driver/error/error.go#L128

**Comment by ca1e** [comment]
thats so helpful! thank you buddy!
