### ISSUE TITLE
Multiple go clients

### ISSUE THREAD

**Issue by lummie** [tikv/client-go#49]
I am totally confused there seems to be two Go clients in existence:
1) `github.com/tikv/client-go` which you would think is the preferred and most up-to-date as it is part of the github.com/tikv project account
and 
2) `github.com/pingcap/tidb/store/tikv` which is used in the tikv.org documentation linked to by `https://github.com/tikv/tikv`  

Can you explain (maybe add to a readme on tikv/client-go) the difference, pros and cons of using either, clarify which is the recommended to be used.

**Comment by disksing** [comment]
`github.com/tikv/client-go` aims to provide a clean library to use tikv. The good side is less dependencies, and the bad side is that it does not have some new features and new interfaces added by `tidb/store/tikv`.
