### ISSUE TITLE
Any way to batch get tso from pd instead of one by one?

### ISSUE THREAD

**Issue by guoxiangCN** [tikv/client-go#523]
Is there any way to batch fetch tso from the pd ?

**Comment by sticnarf** [comment]
The PD client automatically batches get tso so you shouldn't care about the performance. Yet there is no way for you to manually get a batch of timestamps and allocate them by yourself. cc @disksing

**Comment by sticnarf** [comment]
Can you please tell us your use case of batch get tso?

**Comment by guoxiangCN** [comment]
> Can you please tell us your use case of batch get tso?

Our business relies on a monotonically increasing sequence number in the distributed environment. Each time we obtain Tso, we need to generate network interaction with PD. 

When QPS is very high, we need to deal with PD very frequently. Therefore, we want to see if there is a wayto obtain Tso from PD in batches and cache it locally.

**Comment by guoxiangCN** [comment]
We don't care about the timeliness of Tso, we just need monotonic increase。
