### ISSUE TITLE
`updateTiKVSendReqHistogram` is always called with nil resp

### ISSUE THREAD

**Issue by zyguan** [tikv/client-go#558]
[Here](https://github.com/tikv/client-go/pull/536/files#diff-3b1f8149deb45d304c69c856bcd1b9b628961fb6000486cb39172a99cb8de514R455) we try to pass resp to `updateTiKVSendReqHistogram`, however we never assign value to the resp since we always return directly in `sendRequest` (try [this](https://go.dev/play/p/b8GlfmuyFdD)). As a result, metrics like `TiKVRPCNetLatencyHistogram` is actully unavailable.

**Comment by sticnarf** [comment]
To my understanding, the key is not about whether we assign to `resp`... Whether we use a closure matters.

Use a closure but no assignment: https://go.dev/play/p/pnM8dhPd4qj

Assign the return variable but don't use a closure: https://go.dev/play/p/YExnvOLOBF2

**Comment by zyguan** [comment]
Ah, I see, sorry for bothering.
