### ISSUE TITLE
`insertRegionToCache` should remove intersecting regions in the cache

### ISSUE THREAD

**Issue by sticnarf** [tikv/client-go#565]
Our region cache B-Tree uses the start key of the region as the entry key. So, `insertRegionToCache` only replaces the region with the same start key:
https://github.com/tikv/client-go/blob/516cfcdecce865d90ec05dd1cc1de060c35438dc/internal/locate/region_cache.go#L1287

Considering there's a table with lots of regions, the user removes all data from the table. So, PD will finally merge all regions into one. In our region cache implementation, only the first region (containing the table head) is updated, while all other regions still exist in the cache.

When we locate a key near the end of the table, `DescendLessOrEqual` will iterate over all regions that are left in the cache. This will waste a lot of CPU and make region search really slow, and it is also possible to cause lots of unnecessary PD `loadRegion` RPCs.

To solve the problem, when we do `insertRegionToCache`, we should iterate the B-Tree for all regions that intersect with the inserted region and remove them.

This is probably the root cause of https://github.com/tikv/client-go/issues/532

**Comment by chenmin1992** [comment]
I think it is better to remove the rest of regions from region cache wihle region merging. Because although a region has been removed from cache but it is still there, it is not real situation, and I think `insertRegionToCache` is a time-sensitive operation,  it can result in increasing the duration of sql execution, which need to reload region info from PD. Personal opinion, ignore please.

**Comment by sticnarf** [comment]
> I think it is better to remove the rest of regions from region cache wihle region merging. Because although a region has been removed from cache but it is still there, it is not real situation, and I think `insertRegionToCache` is a time-sensitive operation, it can result in increasing the duration of sql execution, which need to reload region info from PD. Personal opinion, ignore please.

Right, it will be better if it's possible. But because client-go is not involved in region merge, it is hard for client-go to get notified when a region is merged.

Deleting in `insertRegionToCache` may be slow, but it's a one-time operation. I think it's mostly acceptable that it happens only once after a lot of regions get merged together.
