### ISSUE TITLE
Upgrade etcd/grpc version

### ISSUE THREAD

**Issue by strahe** [tikv/client-go#63]
tidb current version: https://github.com/pingcap/tidb/blob/master/go.mod#L70

There may be some incompatibilities in the current version：
![image](https://user-images.githubusercontent.com/7932644/102166404-f46a8380-3ec6-11eb-8bf3-d090e459cce1.png)

**Comment by omaskery** [comment]
We encountered this while trying to upgrade one of our projects to use the newest versions of the Go gRPC libraries, `protoc` versions, etc.

I had a brief look into creating a PR to address this but found quite quickly that this is currently all blocked on some stuff going on in the `etcd` Go client library: https://github.com/etcd-io/etcd/pull/12398

**Comment by disksing** [comment]
@omaskery Thank you for raising this issue, I have added it to the list and managed to put the preceding issue to the roadmap schedule of the PD project. Hopefully, we will upgrade it after the PD upgrade is completed before the release.
