### ISSUE TITLE
go get tikv/client-go/config fails with go 1.13

### ISSUE THREAD

**Issue by rajantikare** [tikv/client-go#69]
while getting the go get tikv/client-go/config fails with the below issue on go 1.13

go: finding github.com/tikv/client-go latest
go: finding github.com/tikv/client-go/rawkv latest
go: finding github.com/tikv/client-go/config latest
go: github.com/tikv/client-go@v0.0.0-20210125102738-67fbdfbe1440 requires
	github.com/tikv/pd@v1.1.0-beta.0.20210122094357-c7aac753461a requires
	github.com/pingcap-incubator/tidb-dashboard@v0.0.0-20210104140916-41a0a3a87e75 requires
	gopkg.in/oleiade/reflections.v1@v1.0.0: go.mod has non-....v1 module path "github.com/oleiade/reflections" at revision v1.0.0

**Comment by Xuanwo** [comment]
`gopkg.in/oleiade/reflections.v1` has renamed to `github.com/oleiade/reflections`.

This should be fixed for now as we have updated the dependences.

**Comment by disksing** [comment]
v2.0 should be ok now. If there are more issues please reopen it.
