### ISSUE TITLE
Is there a version mapping table to describe which version of tikv/pd should use which version of client-go

### ISSUE THREAD

**Issue by guoxiangCN** [tikv/client-go#690]
As the title said~

**Comment by Smityz** [comment]
+1, we have discovered that some client and server are not guaranteed to be compatible, such as the v5.3.x server with the latest client. Ref: https://github.com/tikv/client-go/issues/646
Can we maintain a list of supported servers when releasing versions?

**Comment by sticnarf** [comment]
I have been trying to not introducing breaking changes to transactional APIs. So, I expect the latest client to be compatible with any TiKV later than 4.0.

Newer features (e.g. async commit) are enabled through options. If you don't enable them, the client should work with low version TiKV.

I don't think the proto change like in #646 is reasonable. But I'm not so familar with the raw kv, sorry.

**Comment by guoxiangCN** [comment]
> I have been trying to not introducing breaking changes to transactional APIs. So, I expect the latest client to be compatible with any TiKV later than 4.0.
> 
> Newer features (e.g. async commit) are enabled through options. If you don't enable them, the client should work with low version TiKV.
> 
> I don't think the proto change like in #646 is reasonable. But I'm not so familar with the raw kv, sorry.

ok i known, thanks for you reply :)
