### ISSUE TITLE
How to use retry txn like tidb's client `IsTxnRetryableError`

### ISSUE THREAD

**Issue by slow-zhang** [tikv/client-go#73]
In TiDB's TiKV client, there is a funtion `IsTxnRetryableError(err)`, how to check the txn is retryable if I replace it to tikv/client-go?

**Comment by slow-zhang** [comment]
according to [link](https://github.com/tikv/client-go/blob/00eeab450c8cd56d442b4500c4edef77da01d668/txnkv/store/errors.go#L24), `strings.Contains(err.Error(), store.TxnRetryableMark)` maybe a workaround solution

**Comment by disksing** [comment]
> according to [link](https://github.com/tikv/client-go/blob/00eeab450c8cd56d442b4500c4edef77da01d668/txnkv/store/errors.go#L24), `strings.Contains(err.Error(), store.TxnRetryableMark)` maybe a workaround solution

Yes. This is actually how TiDB handles it.
