### ISSUE TITLE
Can txnkv client access API V2 tikv cluster?

### ISSUE THREAD

**Issue by in-han** [tikv/client-go#767]
According to **API V2 RFC** , I think deploying an api-v2 tikv cluster can allow rawkv and txnkv to access at the same time.

Rawkv can access it, but txnkv client get error message.

This is the error message:
`
tikv aborts txn: Error(InvalidKeyMode { cmd: prewrite, storage_api_version: V2, key: "666F6F0000000000FA" })
`
In tikv/client-go/integration_tests, there is no api tests (end to end) for txnkv,   and   there is integration_tests/raw/api_test.go for rawkv.
And I can't get any docuemnt, that shows how to access tikv API V2 by txnkv client.

So there is my question:  
      How can  txnkv client access a  API V2 tikv cluster ?

If anyone can help, I am very grateful.

**Comment by iosmanthus** [comment]
Yes, you could follow the tutorial at https://github.com/tikv/client-go/wiki/API-V2. If there is any question about the API V2, don't hesitate to ask.
