### ISSUE TITLE
Optimize RawKV scan process to improve read throughput

### ISSUE THREAD

**Issue by Smityz** [tikv/client-go#827]
In the current design, the scan process is serial, which has the advantage of ensuring the order of results and simplifying the design. However, in some scenarios, we need to return the data of the required interval to the client as quickly as possible. Therefore, I am considering whether to add a parallel scan function to improve the client's throughput.

**Comment by disksing** [comment]
I think you can start multiple goroutines to concurrently scan, but you may need to determine the scan range for each goroutine based on the data, and also handle the problem of possible duplicate data returned by different goroutines.

**Comment by Smityz** [comment]
Yes, that's the issue. Users are unable to develop a reasonable scanning plan because they are unaware of the data distribution. However, the SDK has sufficient information to formulate a parallel scanning plan between regions.

**Comment by disksing** [comment]
I think you make some valid points. However, I still believe that this feature goes beyond the complexity of the client and you may consider implementing it outside of the client. You can use the ScanRegion interface of PD to obtain the key range of different regions in advance, but you still need to pay attention to the dynamic splitting/merging of regions, which may cause data duplication or loss.

**Comment by Smityz** [comment]
OK, thanks for your help!
