### ISSUE TITLE
When leader is selected as target peer at first, no other replicas could be retied for stale read

### ISSUE THREAD

**Issue by cfzjywxk** [tikv/client-go#906]
When the leader peer is first picked as the target with labels and it's unavailable because of some region errors, the replica selector would keep trying the leader peer but not recover though replica peers may be able to process this request successfully.

For example:
1. consider there are 3AZs with 1 tidb and 1 tikv server in each AZ, and there is a region whose leader peer is in AZ a. 
2. Then a stale read request is triggered by the tidb-server in AZ a, the tikv-server in AZ a is selected as the target peer because of the label configurations. 
3. Meanwhile, network partition happens between the tidb and tikv nodes in AZ a, and when errors are encountered processing stale read requests the leader peer is unconditionally retried. 
4. The leader is unavailable and tidb kept raising pseudo epoch not match errors and retrying those peers.

**Comment by you06** [comment]
#916 fixed this issue, which wll fallback to follower read when leadder is unavailable.

**Comment by cfzjywxk** [comment]
> #916 fixed this issue, which wll fallback to follower read when leadder is unavailable.

@you06 #916 introduces fallback to follower `ServerIsBusy` is returned, the unavailable or rpc error is not processed yet?

**Comment by you06** [comment]
@cfzjywxk also made some changes in #910, which handles unavailable and rpc error.

https://github.com/tikv/client-go/blob/979c4899ab9010341b6db0dd8cfd70f29dceef44/internal/locate/region_request.go#L627-L641

**Comment by cfzjywxk** [comment]
@you06 OK，you cloud close the issue in that PR

**Comment by cfzjywxk** [comment]
@you06 Please close this issue if the master PR is merged.
