### ISSUE TITLE
corner case question: How does TiDB ensure that it does not mistakenly delete ranges that may still have pending writes?

### ISSUE THREAD

**Issue by Yriuns** [tikv/client-go#961]
Chinese Version: https://asktug.com/t/topic/1012767

I thought of a corner case and looked at the TiDB code but couldn't find any specific handling for it, so I'm curious.

Let's assume there is a write transaction T and a GC leader.

We know that the execution order of an optimistic transaction is as follows:

1. Get `start_ts`.
2. Perform read and write operations in TiDB.
3. parallelly prewrite the primary key and secondary keys.
4. Get `commit_ts`.
5. Commit the primary key.
6. Commit the secondary keys.

The execution order of the GC leader is as follows:

1. Calculate the safe point: min(`now() - gc_life_time`, the minimum start_ts of active transactions on each TiDB node).
2. Execute the scan locks request.
3. Execute the resolve locks request.
4. Execute the delete range operation.
5. Clean up MVCC.

Now we assuming the user has dropped an index `idx`, and the online DDL has already progressed to the "none" state, but the schema of transaction `T` is still in the "delete only" state.
Is there a possible sequence of events like this:

0. `T` selects a key in the range corresponding to index `idx` as the primary key.
1. `T`'s prewrite primary & secondary requests timeout on the network, and the session is cleard, so `T.start_ts` is not included in the safe point calculation.
2. The GC leader calculates the safe point as the `now() - gc_life_time`.
3. The GC leader executes the scan locks operation, but it cannot find the on-the-fly secondary locks from step 1.
4. The GC leader executes the resolve locks operation, which also does not handle the locks from step 1.
5. `T`'s prewrite request reaches TiKV and successfully acquires the lock.
6. The GC leader deletes the range of `idx`, which means the primary key is deleted.
7. When resolving the secondary key, it cannot find the primary key due to step 6 and doesn't know whether to commit or rollback.

It seems step 7 will result in a consistency problem, but I thought I missed something important...

**Comment by Yriuns** [comment]
@MyonKeminta @cfzjywxk I'm sorry to bother, but the answer in AskTUG seems wrong, could you please take a look?

**Comment by MyonKeminta** [comment]
Thanks for your asking and being interested about these technical details.

Firstly, you are right that the *delete ranges* performs the deletion without any concern about transactional consistency. All the historical versions will be deleted. I'm sorry for that there seem to be some misunderstanding in that AskTUG channel.

> 5. `T`'s prewrite request reaches TiKV and successfully acquires the lock.

It's actually an issue that a request accessing data that has been GC-ed can still be handled. The better idea is to reject this kind of requests, however we didn't for now.

> 6. The GC leader deletes the range of idx, which means the primary key is deleted.

Yes, this is possible.

> 7. When resolving the secondary key, it cannot find the primary key due to step 6 and doesn't know whether to commit or rollback.

When it cannot find the information about the primary key, the transaction will be considered rolled back. Therefore, the secondary lock will be rolled back. You can consider another case: a transaction T successfully prewrites secondary keys `k2` and `k3`, but crashed before successfully prewriting the primary `k1`. Then it lefts an equivalent result as your example, and we know that in this case the transaction is supposed to be rolled back.

Hope this might help you.

**Comment by Yriuns** [comment]
> Thanks for your asking and being interested about these technical details.
> 
> Firstly, you are right that the _delete ranges_ performs the deletion without any concern about transactional consistency. All the historical versions will be deleted. I'm sorry for that there seem to be some misunderstanding in that AskTUG channel.
> 
> > 5. `T`'s prewrite request reaches TiKV and successfully acquires the lock.
> 
> It's actually an issue that a request accessing data that has been GC-ed can still be handled. The better idea is to reject this kind of requests, however we didn't for now.
> 
> > 6. The GC leader deletes the range of idx, which means the primary key is deleted.
> 
> Yes, this is possible.
> 
> > 7. When resolving the secondary key, it cannot find the primary key due to step 6 and doesn't know whether to commit or rollback.
> 
> When it cannot find the information about the primary key, the transaction will be considered rolled back. Therefore, the secondary lock will be rolled back. You can consider another case: a transaction T successfully prewrites secondary keys `k2` and `k3`, but crashed before successfully prewriting the primary `k1`. Then it lefts an equivalent result as your example, and we know that in this case the transaction is supposed to be rolled back.
> 
> Hope this might help you.

Thank you for your reply!

But I think here is a little different between the case you provide and the issue: When prewrite primary failed, the range that the primary key belong to is still there. However, in the delete range case,  the `ResolveLock` routine may even cannot find the region, i.e. the regions of `idx` might have been deleted in pd. According to the code of `client-go`, when it fail to `locateKey`, it will just return a `err` and do nothing to the secondary key, raher than rollback it.

Is there something I missed?

**Comment by Yriuns** [comment]
> The delete range procedure doesn't have the ability to make the region physically inaccessible. The region won't be deleted from PD.

I see! The whole range in `TiKV` is always continuous, so that `locateKey` should always work. Thanks a lot!

**Comment by MyonKeminta** [comment]
You're welcome. I'll close this issue. Please feel free to reopen if you still have any questions.

**Comment by Yriuns** [comment]
> You're welcome. I'll close this issue. Please feel free to reopen if you still have any questions.

Like you said, I came up with a new question in the weekend🤣. Sorry to bother again.

> When it cannot find the information about the primary key, the transaction will be considered rolled back.

In other words, we must ensure the range of a primary key will **not** be deleted when it still has un-resolved secondary keys.

I try to figure out how TiDB make this, and I thought it's done by the calculation of safe point(mainly by `min_start_ts` mechanism).
Still using this assumption:
> Now we assuming the user has dropped an index idx, and the online DDL has already progressed to the "none" state, but the schema of transaction T is still in the "delete only" state.

In additional, we assume the primary key is committed, and the secondary keys are not yet. We want to prove that no concurrent GC will delete the range of `idx`
- GC leader calculates the safe point before `T` gets its `start_ts`: We have safe point < `T.start_ts`. And `T`'s schema is `delete only`, which indicates that `T.start_ts` < the delete timestamp of range `idx`. Therefore, we have safe point < the delete timestamp of range `idx`, i.e., the range will not be deleted.
- `T` gets its `start_ts` before GC leader calculates the safe point: Since `T` commits the primary later, which means `T` must be alive during the calculation of safe point, i.e., `T.start_ts` must contribute its value in `min_start_ts`. Therefore, we have safe point <= `min_start_ts` <= `T.start_ts` < the delete timestamp of range `idx`. The range will not be deleted either.

Is my proof correct？Thanks a lot!

**Comment by MyonKeminta** [comment]
The `min_start_ts` mechanism you said actually concerns about only alive sessions' states, and once a transaction enters the *committed* state, the session gets out from the transaction, no matter whether the secondaries are completely committed.

The mechanism that actually solves this problem is *resolve locks*. When a round of GC is started with some safepoint, the first step is to run `resolve locks` with the safepoint, which scans all locks whose start_ts <= safepoint, and resolve them. The deleting-range step comes after resolving locks.

**Comment by Yriuns** [comment]
> The `min_start_ts` mechanism you said actually concerns about only alive sessions' states, and once a transaction enters the _committed_ state, the session gets out from the transaction, no matter whether the secondaries are completely committed.
> 
> The mechanism that actually solves this problem is _resolve locks_. When a round of GC is started with some safepoint, the first step is to run `resolve locks` with the safepoint, which scans all locks whose start_ts <= safepoint, and resolve them. The deleting-range step comes after resolving locks.

Thanks for reply! I know the resolve locks phase but I'm worried about such a corner case that it may miss to resolve some locks that it should resolve:

0. `T` get its `start_ts` and selects a key in the range corresponding to index `idx` as the primary key. Then it stucks for a while.
1. The GC leader calculates the safe point
2. The GC leader executes the resolve locks
3. The GC leader executes the resolve locks operation, which will not resolve `T`'s locks since them are not sent yet.
4. `T` resumes and exeutes `Prewrite` successfully
5. `T` commits the primary key successfully
6. The GC leader deletes the range of `idx`, which means the primary key is deleted.
7. When resolving the secondary key, it cannot find the primary key due to step 6 and doesn't know whether to commit or rollback.

I thought the key-point here is to make safe point small enough, so that the step 6 will not happen. I guess it's done by `min_start_ts`, right?
p.s. Step 0 and step 1 can be swapped, which corresponds to the two cases of my proof.

**Comment by MyonKeminta** [comment]
> I thought the key-point here is to make safe point small enough, so that the step 6 will not happen. I guess it's done by min_start_ts, right?

Yes. 

Actually, the possibility that a transaction is stuck at this place for more than 10 minutes without failing is so low that we don't usually consider this as a critical case.

**Comment by Yriuns** [comment]
> > I thought the key-point here is to make safe point small enough, so that the step 6 will not happen. I guess it's done by min_start_ts, right?
> 
> Yes.
> 
> Actually, the possibility that a transaction is stuck at this place for more than 10 minutes without failing is so low that we don't usually consider this as a critical case.

I see. Thanks a lot!
