### ISSUE TITLE
MinSafeTS might be set to MaxUint64 permanently

### ISSUE THREAD

**Issue by JmPotato** [tikv/client-go#991]
If the cluster just bootstraps and the `min-resolved-ts` hasn't been initialized yet, `MinSafeTS` might be set to `MaxUint64`. And since the `MinSafeTS` is not allowed to fall back, it will remain being this value permanently.

https://github.com/tikv/client-go/blob/c8832b846685d303f5afe29e1f8da50c7aff9a2e/tikv/kv.go#L546-L563

**Comment by MimeLyc** [comment]
update

**Comment by HuSharp** [comment]
The core question is the getter 
- we introduce `PD API` to not execute `go func which for KV request`, resulting in not updating `safeTSMap`. 		 
    - `updateMinSafeTS` relies on  `safeTSMap` which makes sense(because actually, we can call `updateMinSafeTS` to `kvReuqestUpdater`[to indicate func base]).
- And we need to update `minsafeTS` to make sure when API fails we can fall back to the original way which is by kv request.
- But the core question is:  **`updateMinSafeTS` will return `maxUnit64` when there is no kv request.**
   - to resolve this question, we need to regard `maxUnit64` as 0 which means there is an initial state.
